apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-team
  namespace: argocd
spec:
  description: Frontend Team
  sourceRepos:
    - https://github.com/KaranPrince/platform-gitops.git
  destinations:
    - namespace: moderor-ui
      server: https://kubernetes.default.svc