apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-team
  namespace: argocd
spec:
  description: Platform Team
  sourceRepos:
    - https://github.com/KaranPrince/platform-gitops.git
  destinations:
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc