apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderor-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moderor-api
  template:
    metadata:
      labels:
        app: moderor-api
    spec:
      containers:
      - name: api
        image: hashicorp/http-echo:1.0
        args:
          - "-text=Moderor API Service"
        ports:
        - containerPort: 1000