apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moderor-notification
  namespace: argocd
spec:
  project: moderor
  source:
    repoURL: https://github.com/KaranPrince/platform-gitops.git
    targetRevision: main
    path: applications/moderor-notification/base
  destination:
    server: https://kubernetes.default.svc
    namespace: moderor-notification
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true