apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderor-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moderor-ui
  template:
    metadata:
      labels:
        app: moderor-ui
    spec:
      containers:
      - name: ui
        image: hashicorp/http-echo:1.0
        args:
          - "-text=Moderor UI Service"
        ports:
        - containerPort: 4000