apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderor-notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moderor-notification
  template:
    metadata:
      labels:
        app: moderor-notification
    spec:
      containers:
      - name: notification
        image: hashicorp/http-echo:1.0
        args:
          - "-text=Moderor Notification Service"
        ports:
        - containerPort: 3000