apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderor-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moderor-auth
  template:
    metadata:
      labels:
        app: moderor-auth
    spec:
      containers:
      - name: auth
        image: hashicorp/http-echo:1.0
        args:
          - "-text=Moderor Authentication Service"
        ports:
        - containerPort: 5678